# Generated by Django 4.1.5 on 2023-01-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم نشاط التطوير المهني')),
                ('auth', models.CharField(max_length=150, unique=True, verbose_name='الجهة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('type', models.CharField(max_length=150, unique=True, verbose_name='نوع النشاط')),
                ('t_dur', models.CharField(max_length=150, unique=True, verbose_name='نوع المدة')),
                ('dur', models.PositiveSmallIntegerField(verbose_name='مدة النشاط')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher', verbose_name='المعلم')),
            ],
        ),
    ]
