# Generated by Django 4.1.5 on 2023-01-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='auth',
            field=models.CharField(max_length=150, verbose_name='الجهة'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=150, verbose_name='اسم نشاط التطوير المهني'),
        ),
        migrations.AlterField(
            model_name='table',
            name='t_dur',
            field=models.CharField(max_length=150, verbose_name='نوع المدة'),
        ),
        migrations.AlterField(
            model_name='table',
            name='type',
            field=models.CharField(max_length=150, verbose_name='نوع النشاط'),
        ),
    ]
